title: Home
views:
  - title: Home
    badges:
      - alarm_control_panel.sector_alarm_02700305
      - binary_sensor.kitchen_water_detector_42
      - binary_sensor.tvattstuga_water_detector_76
      - person.anders_haglund
      - sensor.vader_wind_speed
      - sensor.vader_symbol
      - sensor.vader_temperature
      - sun.sun
    cards:
      - title: Bra att ha scener
        type: glance
        entities:
          - entity: scene.overvaning_mys
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data: 
                entity_id: scene.overvaning_mys
          - entity: scene.vardagsrum_nere_mys
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.vardagsrum_nere_mys
          - entity: scene.vardagsrum_nere_tv
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.vardagsrum_nere_tv 
      - title: Godnatt scener
        type: glance
        entities:
          - entity: scene.julia_sovdags
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.julia_sovdags
          - entity: scene.klara_sovdags
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.klara_sovdags
          - entity: scene.godnatt
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.godnatt
      - title: Markiser
        type: entities
        entities:
          - cover.somfy_framsida
          - cover.somfy_baksida 
          - cover.somfy_fa_sovrum
          - cover.somfy_julia
          - cover.somfy_klara
          - cover.somfy_kok
          - cover.somfy_vardagsrum_uppe 
      - title: Kök
        type: entities
        entities:
          - light.kitchen_bulb_1
          - cover.somfy_kok
      - title: FA Sovrum
        type: entities
        entities:
          - light.fa_bulb_1
          - light.fa_bulb_2
          - light.fa_bulb_3
          - light.fa_spot_1
          - light.fa_spot_2
          - light.fa_spot_3
          - light.fa_spot_4
          - cover.somfy_fa_sovrum
      - title: Vardagsrum uppe
        type: entities
        entities:
          - switch.lilla_bollen_uppe
          - switch.svarta_skrivbordslampan_9
          - cover.somfy_vardagsrum_uppe
      - title: Vardagsrum nere
        type: entities
        entities:
          - light.dimmer_tavelvagg_matbord_31
          - light.dimmer_tavelvagg_tv_18
          - light.dimmer_svarta_tavlan_5
          - light.matbord_dimmer_14
          - switch.verpan_7
          - switch.svart_vipplampa_36
          - light.stora_bollen 
      - title: Trappa
        type: entities
        entities:
          - light.ballonglampa
      - title: Julias rum
        type: entities
        entities:
          - scene.julia_avkoppling
          - light.julia_spot_hoger_1
          - light.julia_spot_hoger_2
          - light.julia_spot_vanster_1
          - light.julia_spot_vanster_2
          - light.julia_spot_vanster_3
          - cover.somfy_julia
      - title: Klaras rum
        type: entities
        entities:
          - scene.klara_avkoppling 
          - light.klara_spot_hoger_1
          - light.klara_spot_hoger_2
          - light.klara_spot_vanster_1
          - light.klara_spot_vanster_2
          - cover.somfy_klara
      - title: Utomhus
        type: entities
        entities:
          - switch.ljusslingor_pergola_45
          - switch.utebelysning_bak_44
      - entity: alarm_control_panel.sector_alarm_02700305
        states:
          - arm_home
          - arm_away
        type: alarm-panel
        name: Larm
  - title: Devices
    cards:
      - title: Switch
        type: entities
        entities:
          - switch.kaninlampa_50
          - switch.lilla_bollen_fa_38
          - switch.lilla_bollen_uppe
          - switch.ljusslingor_pergola_45
          - switch.molnlampa_28
          - switch.outside_2_relay_43
          - switch.stars_30
          - switch.svart_vipplampa_36
          - switch.svarta_lampan_8
          - switch.svarta_skrivbordslampan_9
          - switch.utebelysning_bak_44
          - switch.verpan_7
      - title: lights
        type: entities
        entities:
          - light.ballonglampa
          - light.dimmer_hall_39
          - light.dimmer_svarta_tavlan_5
          - light.dimmer_tavelvagg_matbord_31
          - light.dimmer_tavelvagg_tv_18
          - light.entrelampa
          - light.fa_bulb_1 
          - light.fa_bulb_2
          - light.fa_bulb_3
          - light.fa_spot_1
          - light.fa_spot_2
          - light.fa_spot_3
          - light.fa_spot_4
          - light.julia_spot_hoger_1
          - light.julia_spot_hoger_2
          - light.julia_spot_vanster_1
          - light.julia_spot_vanster_2
          - light.julia_spot_vanster_3
          - light.kitchen_bulb_1
          - light.klara_spot_hoger_1
          - light.klara_spot_hoger_2
          - light.klara_spot_vanster_1
  - title: Scenes
    cards:
      - title: FA sovrum
        type: entities
        entities:
          - scene.fa_fokus
          - scene.fa_mys
          - scene.fa_vardag
      - title: Sovdags
        type: entities
        entities:
          - scene.godnatt
          - scene.julia_sovdags
          - scene.klara_sovdags
      - title: Julia
        type: entities
        entities:
          - scene.julia_avkoppling
          - scene.julia_fokus
          - scene.julia_sovdags
          - scene.julia_vardag
      - title: Klara
        type: entities
        entities:
          - scene.klara_avkoppling
          - scene.klara_fokus
          - scene.klara_sovdags
          - scene.klara_vardag
      - title: Kök
        type: entities
        entities:
          - scene.kok_fokus
          - scene.kok_mys
          - scene.kok_pa
          - scene.kok_vardagsmorgon  
      - title: Övervåning
        type: entities
        entities:
          - scene.overvaning_av
          - scene.overvaning_mys
          - scene.overvaning_pa
      - title: Utomhus
        type: entities
        entities:
          - scene.pergola_pa
      - title: Vardagsrum
        type: entities
        entities:
          - scene.vardagsrum_nere_grundbelysning
          - scene.vardagsrum_nere_mys
          - scene.vardagsrum_nere_pa
          - scene.vardagsrum_nere_tv
      - title: Vardagsrum uppe
        type: entities
        entities:
          - scene.vardagsrum_uppe_tv
      - title: Generellt
        type: entities
        entities:
          - scene.hela_huset_av
          - scene.hus_grundbelysning
          - scene.nagon_kommer_hem
          - scene.nedervaning_av
          - scene.vardagsmorgon
  - title: automationer
    cards:
      - title: automationer
        type: entities
        entities:
          - automation.alla_borta
          - automation.godnatt_kolla_larm
          - automation.ingen_hemma_satta_pa_grundbelysning
          - automation.nagon_kommer_hem
          - automation.satta_pa_entrebelysning
          - automation.stanga_av_entrebelysning
          - automation.vardagsmorgon
          - automation.tvattstuga_vattenlarm
          - automation.kok_vattenlarm
  - title: Media players
    cards:
      - title: Chromecasts
        type: entities
        entities:
          - media_player.all_speakers
          - media_player.downstairs_speakers
          - media_player.kitchen_speaker
          - media_player.living_room_google_mini
          - media_player.living_room_speaker
          - media_player.tv_nere
          - media_player.tv_uppe
          - media_player.upstairs_google_mini 
