alias: Alla borta
trigger:
  - platform: state
    entity_id: alarm_control_panel.sector_alarm_02700305
    to: 'armed_away'
action:
  - service: homeassistant.turn_off
    entity_id:
      - group.julias_room
      - group.klaras_room
      - group.fa_room
      - group.upstairs_livingroom
      - group.downstairs_livingroom
      - group.kitchen
      - light.dimmer_hall_39
      - switch.ljusslingor_pergola_45
  - service: notify.pushbullet
    data:
      message: 'Alla borta'
