alias: "Alla borta"
trigger:
  - platform: state
    entity_id: alarm_control_panel.sector_alarm_02700305
    to: 'armed_away'
action:
  - service: homeassistant.turn_off
    entity_id:
      - group.julias_rum
      - group.klaras_rum
      - group.fa_room
      - group.upstairs_livingroom
      - group.downstairs_livingroom
      - group.kitchen
      - group.hall
      - group.pergola  
  - service: notify.slack
    data:
      message: 'Alla borta, slacker ner'
