alias: "Daligt vader - grundbelysning"
trigger: 
  -  platform: sun 
     event: sunset
     offset: -02:00:00 
condition: 
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.weather_cloudiness 
      above: "50" 
    - condition:
      entity_id: alarm_control_panel.sector_alarm_02700305
      state: 'disarmed'      
action: 
  - service: scene.turn_on
    entity_id: scene.hus_grundbelysning 
  - service: notify.slack
    data:
      message: 'Dialigt vader automation triggad'  

