alias: 'Satta pa entrebelysning'
trigger:
  platform: sun
  event: sunset
  offset: '-00:15:00'
action:
  - service: scene.turn_on 
    entity_id: scene.entrebelysning_pa
  - service: notify.slack
    data:
      message: 'Entrebelysning pa' 
