alias: Godnatt - kolla larm
trigger:
  - platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.godnatt
      domain: scene
      service: turn_on
condition:
  condition: state
  entity_id: alarm_control_panel.sector_alarm_02700305
  state: 'disarmed'
action:
  - service: notify.pushbullet
    data:
      message: 'Godnatt triggat: Larm inte påslaget'
  - service: notify.slack
    data:
      message: 'Godnatt triggat: Larm inte påslaget'
