alias: 'Godnatt kolla Klaras surplatta'
trigger:
  - platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.godnatt_kolla_larm
      domain: scene
      service: turn_on
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.ipad_battery_level
      below: 99 
    - condition: state
      entity_id: sensor.ipad_battery_state
      state: 'Unplugged'
action:
  - service: notify.slack
    data:
      message: 'Klaras surfplatta har lågt batteri: {{states("sensor.ipad_battery_level")}}'
