alias: Tvättstuga vattenlarm
trigger:
  - platform: state
    entity_id: binary_sensor.tvattstuga_water_detector_76 
    to: 'on'
action:
  - service: notify.pushbullet
    data:
      message: 'Vatten detekterat i tvättstugn'
  - service: notify.slack
    data:
      message: 'Vatten detekterat i tvättstugn'
