alias: "Kök vattenlarm"
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_water_detector_42
    to: 'on'
action:
  - service: notify.pushbullet
    data:
      message: 'Vatten detekterat i köket'
  - service: notify.slack
    data:
      message: 'Vatten detekterat i köket'
